name: bibliotecamobile
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Bloc for state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  # Value equality
  equatable: ^2.0.5
  get_it: ^7.2.0
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  # Local cache
  shared_preferences: ^0.5.6
  # Service locator
  flutter_localizations: 
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.1

flutter:
  uses-material-design: true
  generate: true